version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
    ignore:
      - dependency-name: "eslint"
        versions: [">= 10.0.0"]
