import { app, BrowserWindow, ipcMain } from 'electron';
import { AzureDevOpsService } from './services/azureDevOpsService';
import { CopilotService } from './services/copilotService';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

interface AppSettings {
  azureOrg?: string;
  azureProject?: string;
  azurePat?: string;
  copilotToken?: string;
}

// Global store instance to be initialized dynamically
let store: any;

// Initialization helper for ESM dependencies in CJS
async function initStore() {
  if (!store) {
    const Store = (await import('electron-store')).default;
    store = new Store();
  }
  return store;
}

// Global service instances
let azureService: AzureDevOpsService | null = null;
const copilotService = new CopilotService();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// IPC Handlers
ipcMain.handle('get-settings', async () => {
  const s = await initStore();
  return s.get('settings');
});

ipcMain.handle('save-settings', async (event, settings: AppSettings) => {
  const s = await initStore();
  s.set('settings', settings);
  
  // Invalidate azure service so it gets re-created on the next fetch with new credentials
  azureService = null;
  
  return { success: true };
});

ipcMain.handle('fetch-ticket', async (event, ticketId) => {
  const s = await initStore();
  const settings = s.get('settings') as AppSettings;
  if (!settings || !settings.azureOrg || !settings.azurePat) {
    throw new Error('Azure DevOps settings are missing.');
  }

  if (!azureService) {
    azureService = new AzureDevOpsService(settings.azureOrg, settings.azurePat);
  }
  return azureService.fetchTicket(ticketId);
});

ipcMain.handle('generate-test-cases', async (event, ticketData, additionalContext) => {
  return copilotService.generateTestCases(ticketData, additionalContext);
});

ipcMain.handle('check-copilot-auth', async () => {
  return copilotService.checkAuthStatus();
});

ipcMain.handle('add-comment', async (event, ticketId, text) => {
  if (!azureService) throw new Error('Azure DevOps service not initialized.');
  return azureService.addComment(ticketId, text);
});

ipcMain.handle('add-child-task', async (event, parentTicketId, title, description) => {
  if (!azureService) throw new Error('Azure DevOps service not initialized.');
  return azureService.addChildTask(parentTicketId, title, description);
});

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 850,
    width: 1200,
    titleBarStyle: 'hidden',
    titleBarOverlay: process.platform === 'win32' ? {
      color: '#212529',
      symbolColor: '#ffffff',
      height: 44
    } : false,
    trafficLightPosition: { x: 15, y: 15 }, // Adjusted for 44px height
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

app.on('will-quit', async () => {
  await copilotService.cleanup();
});
